################################################################################
# Build pipeline
################################################################################

docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v2.1.0-oasis4:
    image: "oasislabs/testing:0.3.0"
    always_pull: true
    workdir: /workdir
    volumes:
      - .:/workdir
      - /var/lib/buildkite-agent/.ssh:/root/.ssh
      # Shared Rust artifacts cache.
      - /tmp/cargo_cache:/cargo_cache
      # Shared Rust package checkouts directory.
      - /tmp/cargo_pkg/git:/root/.cargo/git
      - /tmp/cargo_pkg/registry:/root/.cargo/registry
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_INCREMENTAL=/cargo_cache"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
      - "EKIDEN_BRANCH=master"
      - "RUNTIME_BRANCH=master"
      - "DEVELOPER_GATEWAY_BRANCH=master"
    propagate-environment: true
    unconfined: true

steps:
  - label: Run Tests
    parallelism: 4
    command:
      - .buildkite/scripts/test_e2e.sh -t e2e-tm-committee-e2e-tests
    timeout_in_minutes: 25
    # use default: exit-status: "*" and retry limit of 2
    retry:
      automatic: true
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration
