[package]
name = "deployed-abi"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
oasis-std = "0.1"

[patch.crates-io]
oasis-std = { path = "/oasis/Projects/platform/oasis-std" }
